routes/web.php
<?php

use App\Http\Controllers\GameController;
use App\Http\Controllers\PlayerController;
use App\Http\Controllers\ScoreController;
use App\Models\Game;
use App\Models\Player;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Login route
Route::get('/', function () {
    return view('welcome');
});
//Authentication for routes
Auth::routes();

//Home Route
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//Game route
Route::resource('game', GameController::class);

//Scoreboard route
Route::resource('scoreboard', ScoreController::class);

//Players route
Route::resource('players', PlayerController::class);

////Users route
//Route::resource('game', GameController::class);

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    use HasFactory;
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Models\Game;
use App\Http\Requests\StoreGameRequest;
use App\Http\Requests\UpdateGameRequest;

class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('games.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreGameRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreGameRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function show(Game $game)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function edit(Game $game)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateGameRequest  $request
     * @param  \App\Models\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateGameRequest $request, Game $game)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function destroy(Game $game)
    {
        //
    }
}

resources/views/games/index.blade.php
<!DOCTYPE html>
<html>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>



<div class="w3-container w3-green">
    @if (Route::has('login'))
        <div class="hidden fixed top-0 right-0 px-6 py-4 sm:block">
            @auth
                <a href="{{ url('/home') }}" class="text-sm text-gray-700 dark:text-gray-500 underline">Home</a>
            @else
                <a href="{{ route('login') }}" class="text-sm text-gray-700 dark:text-gray-500 underline">Log in</a>

                @if (Route::has('register'))
                    <a href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 dark:text-gray-500 underline">Register</a>
                @endif
            @endauth
                <a href="{{ url('/') }}" class="ml-4 text-sm text-gray-700 dark:text-gray-500 underline">Back to home</a>
        </div>
    @endif
    <h1>Project's Development</h1>
    <p>sup</p>
</div>

<div class="w3-row-padding">
    <div class="w3-third">
        <h2><a href="{{ route('players.index') }}" class="text-md text-gray-700 dark:text-gray-500 underline">See all Players</a></h2>
        <p>(This needs to be filled in someday)</p>
        <p>A slice of heaven. O for awesome, this chocka full cuzzie is as rip-off as a cracker.
            Meanwhile, in behind the bicycle shed, Hercules Morse, as big as a horse
            and Mrs Falani were up to no good with a bunch of crook pikelets.
            Meanwhile, at the black singlet woolshed party, not even au, sort your drinking out.</p>

    </div>

    <div class="w3-third">
        <h2><a href="{{ route('scoreboard.index') }}" class="text-md text-gray-700 dark:text-gray-500 underline">See Scoreboard</a></h2>
        <p>(This needs to be filled in someday)</p>
        <p>A slice of heaven. O for awesome, this chocka full cuzzie is as rip-off as a cracker.
            Meanwhile, in behind the bicycle shed, Hercules Morse, as big as a horse
            and Mrs Falani were up to no good with a bunch of crook pikelets.
            Meanwhile, at the black singlet woolshed party, not even au, sort your drinking out.</p>
    </div>

    <div class="w3-third">
        <h2><a href="{{ url('/home')  }}" class="text-md text-gray-700 dark:text-gray-500 underline">Game Rules</a></h2>
        <p>(This needs to be filled in someday)</p>
        <p>A slice of heaven. O for awesome, this chocka full cuzzie is as rip-off as a cracker.
            Meanwhile, in behind the bicycle shed, Hercules Morse, as big as a horse
            and Mrs Falani were up to no good with a bunch of crook pikelets.
            Meanwhile, at the black singlet woolshed party, not even au, sort your drinking out.</p>
    </div>
</div>

</body>
</html>